version: '3.9'

services:
  postgres:
    image: postgres:15.5
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass@word1
      - POSTGRES_USER=postgres
      # - POSTGRES_DB=citizix_db